=== google/skia-buildbot/perf/go/ingest/format/formatSchema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://go.skia.org/infra/perf/go/ingest/format/format",
  "$ref": "#/$defs/Format",
  "$defs": {
    "Format": {
      "properties": {
        "version": {
          "type": "integer"
        },
        "git_hash": {
          "type": "string"
        },
        "issue": {
          "type": "string"
        },
        "patchset": {
          "type": "string"
        },
        "key": {
          "patternProperties": {
            ".*": {
              "type": "string"
            }
          },
          "type": "object"
        },
        "results": {
          "items": {
            "$ref": "#/$defs/Result"
          },
          "type": "array"
        },
        "links": {
          "patternProperties": {
            ".*": {
              "type": "string"
            }
          },
          "type": "object"
        }
      },
      "additionalProperties": false,
      "type": "object",
      "required": [
        "version",
        "git_hash",
        "results"
      ]
    },
    "Result": {
      "properties": {
        "key": {
          "patternProperties": {
            ".*": {
              "type": "string"
            }
          },
          "type": "object"
        },
        "measurement": {
          "type": "number"
        },
        "measurements": {
          "patternProperties": {
            ".*": {
              "items": {
                "$ref": "#/$defs/SingleMeasurement"
              },
              "type": "array"
            }
          },
          "type": "object"
        }
      },
      "additionalProperties": false,
      "type": "object",
      "required": [
        "key"
      ]
    },
    "SingleMeasurement": {
      "properties": {
        "value": {
          "type": "string"
        },
        "measurement": {
          "type": "number"
        },
        "links": {
          "patternProperties": {
            ".*": {
              "type": "string"
            }
          },
          "type": "object"
        }
      },
      "additionalProperties": false,
      "type": "object",
      "required": [
        "value",
        "measurement"
      ]
    }
  }
}

=== google/skia-buildbot/perf/go/ingest/parser/testdata/version_1/success.json
{
  "version": 1,
  "git_hash": "fe4a4029a080bc955e9588d05a6cd9eb490845d4",
  "key": {
    "arch": "x86",
    "branch": "some-branch-name",
    "config": "meta",
    "gpu": "GTX660",
    "model": "ShuttleA",
    "os": "Ubuntu12",
    "system": "UNIX"
  },
  "results": [
    {
      "key": {
        "test": "memory_usage_0_0",
        "sub_result": "max_rss_mb"
      },
      "measurements": {
        "sub_result": [
          {
            "value": "max_rss_mb",
            "measurement": 858
          },
          {
            "value": "min_rss_mb",
            "measurement": 127
          }
        ]
      }
    },
    {
      "key": {
        "test": "DeferredSurfaceCopy_discardable_640_480",
        "source_type": "bench",
        "sub_result": "min_ms"
      },
      "measurements": {
        "config": [
          {
            "value": "8888",
            "measurement": 2.223606
          },
          {
            "value": "565",
            "measurement": 2.215988
          },
          {
            "value": "gpu",
            "measurement": 0.115713274509804
          }
        ]
      }
    }
  ]
}

=== google/skia-buildbot/perf/go/ingest/parser/testdata/version_1/with_commit_number.json
{
  "version": 1,
  "git_hash": "CP:727901",
  "issue": "327697",
  "patchset": "1",
  "key": {
    "arch": "x86",
    "branch": "some-branch-name",
    "config": "meta",
    "gpu": "GTX660",
    "model": "ShuttleA",
    "os": "Ubuntu12",
    "system": "UNIX"
  },
  "results": [
    {
      "key": {
        "test": "memory+usage_0_0",
        "sub_result": "max_rss_mb"
      },
      "measurement": 858
    },
    {
      "key": {
        "test": "DeferredSurfaceCopy_discardable_640_480",
        "source_type": "bench",
        "sub_result": "min+ms"
      },
      "measurements": {
        "config": [
          {
            "value": "8888",
            "measurement": 2.223606
          },
          {
            "value": "565",
            "measurement": 2.215988
          },
          {
            "value": "gpu",
            "measurement": 0.115713274509804
          }
        ]
      }
    }
  ],
  "links": {
    "link1": "www.google.com"
  }
}

=== google/skia-buildbot/perf/go/ingest/parser/testdata/new_format.json
{
  "version": 1,
  "git_hash": "fe4a4029a080bc955e9588d05a6cd9eb490845d4",
  "key": {
    "arch": "x86",
    "branch": "some-branch-name",
    "config": "meta",
    "gpu": "GTX660",
    "model": "ShuttleA",
    "os": "Ubuntu12",
    "system": "UNIX"
  },
  "results": [
    {
      "key": {
        "test": "memory_usage_0_0",
        "sub_result": "max_rss_mb"
      },
      "measurements": {
        "sub_result": {
          "max_rss_mb": 848,
          "min_rss_mb": 127
        }
      }
    },
    {
      "key": {
        "test": "DeferredSurfaceCopy_discardable_640_480",
        "source_type": "bench",
        "sub_result": "min_ms"
      },
      "measurements": {
        "config": {
          "8888": 2.223606,
          "565": 2.215988,
          "gpu": 0.115713274509804
        }
      }
    }
  ]
}
