=== google/skia-buildbot/perf/go/config/validate/instanceConfigSchema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://go.skia.org/infra/perf/go/config/instance-config",
  "$ref": "#/$defs/InstanceConfig",
  "$defs": {
    "AnomalyConfig": {
      "properties": {
        "settling_time": {
          "$ref": "#/$defs/DurationAsString"
        },
        "default_refiner": {
          "type": "string"
        },
        "stepfit_unaligned": {
          "type": "boolean"
        },
        "process_alert_configs_worker_count": {
          "type": "integer"
        },
        "backfill_topic_name": {
          "type": "string"
        },
        "backfill_concurrency": {
          "type": "integer"
        }
      },
      "additionalProperties": false,
      "type": "object"
    },
    "ApplyDefault": {
      "properties": {
        "param": {
          "type": "string"
        },
        "values": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "select_only_first": {
          "type": "boolean"
        }
      },
      "additionalProperties": false,
      "type": "object",
      "required": [
        "param",
        "values",
        "select_only_first"
      ]
    },
    "AuthConfig": {
      "properties": {
        "header_name": {
          "type": "string"
        },
        "email_regex": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "type": "object",
      "required": [
        "header_name"
      ]
    },
    "CacheConfig": {
      "properties": {
        "memcached_servers": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "namespace": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "type": "object",
      "required": [
        "memcached_servers",
        "namespace"
      ]
    },
    "ConditionalDefaultRule": {
      "properties": {
        "trigger": {
          "$ref": "#/$defs/TriggerCondition"
        },
        "apply": {
          "items": {
            "$ref": "#/$defs/ApplyDefault"
          },
          "type": "array"
        }
      },
      "additionalProperties": false,
      "type": "object",
      "required": [
        "trigger",
        "apply"
      ]
    },
    "DataPointConfig": {
      "properties": {
        "keys_for_commit_range": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "keys_for_useful_links": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "skip_commit_detail_display": {
          "type": "boolean"
        },
        "enable_point_links": {
          "type": "boolean"
        },
        "show_json_file_display": {
          "type": "boolean"
        },
        "always_show_commit_info": {
          "type": "boolean"
        }
      },
      "additionalProperties": false,
      "type": "object"
    },
    "DataStoreConfig": {
      "properties": {
        "datastore_type": {
          "type": "string"
        },
        "connection_string": {
          "type": "string"
        },
        "tile_size": {
          "type": "integer"
        },
        "cache": {
          "$ref": "#/$defs/CacheConfig"
        },
        "enable_follower_reads": {
          "type": "boolean"
        },
        "min_db_connections": {
          "type": "integer"
        },
        "query_traces_pool_size": {
          "type": "integer"
        },
        "query_traces_chunk_size": {
          "type": "integer"
        },
        "traceparams_param_indexes": {
          "items": {
            "type": "string"
          },
          "type": "array"
        }
      },
      "additionalProperties": false,
      "type": "object",
      "required": [
        "datastore_type",
        "connection_string",
        "tile_size"
      ]
    },
    "DurationAsString": {
      "type": "string",
      "title": "Duration",
      "description": "A golang time.Duration serialized as a string."
    },
    "Experiments": {
      "properties": {
        "override_bug_component": {
          "type": "boolean"
        },
        "remove_default_stat_value": {
          "type": "boolean"
        },
        "enable_skia_bridge_aggregation": {
          "type": "boolean"
        },
        "preflight_subqueries_for_existing_keys": {
          "type": "boolean"
        },
        "progress_use_redis_cache": {
          "type": "boolean"
        },
        "regressions_trace_id_field": {
          "type": "boolean"
        },
        "df_iter_trace_slicer": {
          "type": "boolean"
        },
        "trace_transform": {
          "type": "boolean"
        }
      },
      "additionalProperties": false,
      "type": "object"
    },
    "ExtraLinks": {
      "properties": {
        "name": {
          "type": "string"
        },
        "title": {
          "type": "string"
        },
        "links": {
          "items": {
            "$ref": "#/$defs/FavoritesSectionLinkConfig"
          },
          "type": "array"
        }
      },
      "additionalProperties": false,
      "type": "object",
      "required": [
        "name",
        "title",
        "links"
      ]
    },
    "Favorites": {
      "properties": {
        "sections": {
          "items": {
            "$ref": "#/$defs/FavoritesSectionConfig"
          },
          "type": "array"
        }
      },
      "additionalProperties": false,
      "type": "object",
      "required": [
        "sections"
      ]
    },
    "FavoritesSectionConfig": {
      "properties": {
        "name": {
          "type": "string"
        },
        "links": {
          "items": {
            "$ref": "#/$defs/FavoritesSectionLinkConfig"
          },
          "type": "array"
        }
      },
      "additionalProperties": false,
      "type": "object",
      "required": [
        "name",
        "links"
      ]
    },
    "FavoritesSectionLinkConfig": {
      "properties": {
        "id": {
          "type": "string"
        },
        "text": {
          "type": "string"
        },
        "href": {
          "type": "string"
        },
        "description": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "type": "object",
      "required": [
        "text",
        "href",
        "description"
      ]
    },
    "GitRepoConfig": {
      "properties": {
        "git_auth_type": {
          "type": "string"
        },
        "provider": {
          "type": "string"
        },
        "start_commit": {
          "type": "string"
        },
        "url": {
          "type": "string"
        },
        "dir": {
          "type": "string"
        },
        "file_change_marker": {
          "type": "string"
        },
        "debounce_commit_url": {
          "type": "boolean"
        },
        "commit_url": {
          "type": "string"
        },
        "commit_number_regex": {
          "type": "string"
        },
        "branch": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "type": "object",
      "required": [
        "provider",
        "url",
        "dir"
      ]
    },
    "IngestionConfig": {
      "properties": {
        "source_config": {
          "$ref": "#/$defs/SourceConfig"
        },
        "branches": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "file_ingestion_pubsub_topic_name": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "type": "object",
      "required": [
        "source_config",
        "branches",
        "file_ingestion_pubsub_topic_name"
      ]
    },
    "InstanceConfig": {
      "properties": {
        "URL": {
          "type": "string"
        },
        "instance_name": {
          "type": "string"
        },
        "header_image_url": {
          "type": "string"
        },
        "landing_page_rel_path": {
          "type": "string"
        },
        "backend_host_url": {
          "type": "string"
        },
        "allowed_hosts": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "contact": {
          "type": "string"
        },
        "invalid_param_char_regex": {
          "type": "string"
        },
        "fetch_chrome_perf_anomalies": {
          "type": "boolean"
        },
        "fetch_anomalies_from_sql": {
          "type": "boolean"
        },
        "switch_between_anomaly_sources": {
          "type": "boolean"
        },
        "feedback_url": {
          "type": "string"
        },
        "chat_url": {
          "type": "string"
        },
        "help_url_override": {
          "type": "string"
        },
        "bug_host_url": {
          "type": "string"
        },
        "favorites": {
          "$ref": "#/$defs/Favorites"
        },
        "extra_links": {
          "$ref": "#/$defs/ExtraLinks"
        },
        "filter_parent_traces": {
          "type": "boolean"
        },
        "trace_sample_proportion": {
          "type": "number"
        },
        "trace_format": {
          "type": "string"
        },
        "need_alert_action": {
          "type": "boolean"
        },
        "use_regression2_schema": {
          "type": "boolean"
        },
        "auth_config": {
          "$ref": "#/$defs/AuthConfig"
        },
        "data_store_config": {
          "$ref": "#/$defs/DataStoreConfig"
        },
        "ingestion_config": {
          "$ref": "#/$defs/IngestionConfig"
        },
        "git_repo_config": {
          "$ref": "#/$defs/GitRepoConfig"
        },
        "notify_config": {
          "$ref": "#/$defs/NotifyConfig"
        },
        "issue_tracker_config": {
          "$ref": "#/$defs/IssueTrackerConfig"
        },
        "anomaly_config": {
          "$ref": "#/$defs/AnomalyConfig"
        },
        "query_config": {
          "$ref": "#/$defs/QueryConfig"
        },
        "temporal_config": {
          "$ref": "#/$defs/TemporalConfig"
        },
        "data_point_config": {
          "$ref": "#/$defs/DataPointConfig"
        },
        "visibility_config": {
          "$ref": "#/$defs/VisibilityConfig"
        },
        "enable_sheriff_config": {
          "type": "boolean"
        },
        "sheriff_configs_to_notify": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "maintenance_config": {
          "$ref": "#/$defs/MaintenanceConfig"
        },
        "ga_measurement_id": {
          "type": "string"
        },
        "new_alerts_page": {
          "type": "boolean"
        },
        "optimize_sqltracestore": {
          "type": "boolean"
        },
        "experiments": {
          "$ref": "#/$defs/Experiments"
        },
        "show_triage_link": {
          "type": "boolean"
        },
        "show_bisect_btn": {
          "type": "boolean"
        },
        "show_hash_ranges_in_tooltip": {
          "type": "boolean"
        },
        "allow_multiple_regressions_per_alert_id": {
          "type": "boolean"
        },
        "enable_v2_ui": {
          "type": "boolean"
        },
        "default_to_explore_v2": {
          "type": "boolean"
        },
        "default_to_manual_plot_mode": {
          "type": "boolean"
        },
        "demo": {
          "type": "boolean"
        }
      },
      "additionalProperties": false,
      "type": "object",
      "required": [
        "URL",
        "contact",
        "data_store_config",
        "ingestion_config",
        "git_repo_config",
        "notify_config"
      ]
    },
    "IssueTrackerConfig": {
      "properties": {
        "notification_type": {
          "type": "string"
        },
        "issue_tracker_api_key_secret_project": {
          "type": "string"
        },
        "issue_tracker_api_key_secret_name": {
          "type": "string"
        },
        "culprit_subject": {
          "type": "string"
        },
        "culprit_body": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "anomaly_report_subject": {
          "type": "string"
        },
        "anomaly_report_body": {
          "items": {
            "type": "string"
          },
          "type": "array"
        }
      },
      "additionalProperties": false,
      "type": "object",
      "required": [
        "notification_type"
      ]
    },
    "MaintenanceConfig": {
      "properties": {
        "gitiles_repo_url": {
          "type": "string"
        },
        "sheriff_config_path": {
          "type": "string"
        },
        "fallback_to_lucicfg": {
          "type": "boolean"
        }
      },
      "additionalProperties": false,
      "type": "object",
      "required": [
        "fallback_to_lucicfg"
      ]
    },
    "NotifyConfig": {
      "properties": {
        "notifications": {
          "type": "string"
        },
        "subject": {
          "type": "string"
        },
        "body": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "missing_subject": {
          "type": "string"
        },
        "missing_body": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "data_provider": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "type": "object",
      "required": [
        "notifications"
      ]
    },
    "QueryCacheConfig": {
      "properties": {
        "type": {
          "type": "string"
        },
        "level1_cache_key": {
          "type": "string"
        },
        "level1_cache_values": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "level2_cache_key": {
          "type": "string"
        },
        "level2_cache_values": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "enabled": {
          "type": "boolean"
        }
      },
      "additionalProperties": false,
      "type": "object",
      "required": [
        "type"
      ]
    },
    "QueryConfig": {
      "properties": {
        "include_params": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "default_param_selections": {
          "patternProperties": {
            ".*": {
              "items": {
                "type": "string"
              },
              "type": "array"
            }
          },
          "type": "object"
        },
        "default_url_values": {
          "patternProperties": {
            ".*": {
              "type": "string"
            }
          },
          "type": "object"
        },
        "cache_config": {
          "$ref": "#/$defs/QueryCacheConfig"
        },
        "redis_config": {
          "$ref": "#/$defs/RedisConfig"
        },
        "query_commit_chunk_size": {
          "type": "integer"
        },
        "max_empty_tiles": {
          "type": "integer"
        },
        "default_range": {
          "type": "integer"
        },
        "default_xaxis_domain": {
          "type": "string"
        },
        "conditional_defaults": {
          "items": {
            "$ref": "#/$defs/ConditionalDefaultRule"
          },
          "type": "array"
        },
        "default_trigger_priority": {
          "patternProperties": {
            ".*": {
              "items": {
                "type": "string"
              },
              "type": "array"
            }
          },
          "type": "object"
        }
      },
      "additionalProperties": false,
      "type": "object"
    },
    "RedisConfig": {
      "properties": {
        "project": {
          "type": "string"
        },
        "zone": {
          "type": "string"
        },
        "instance": {
          "type": "string"
        },
        "cache_expiration_minutes": {
          "type": "integer"
        }
      },
      "additionalProperties": false,
      "type": "object"
    },
    "SourceConfig": {
      "properties": {
        "source_type": {
          "type": "string"
        },
        "project": {
          "type": "string"
        },
        "topic": {
          "type": "string"
        },
        "subscription": {
          "type": "string"
        },
        "dl_topic": {
          "type": "string"
        },
        "dl_subscription": {
          "type": "string"
        },
        "sources": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "reject_if_name_matches": {
          "type": "string"
        },
        "accept_if_name_matches": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "type": "object",
      "required": [
        "source_type",
        "project",
        "topic",
        "subscription",
        "sources"
      ]
    },
    "TemporalConfig": {
      "properties": {
        "host_port": {
          "type": "string"
        },
        "namespace": {
          "type": "string"
        },
        "grouping_task_queue": {
          "type": "string"
        },
        "pinpoint_task_queue": {
          "type": "string"
        },
        "wait_time_for_anomaly_clustering_window": {
          "$ref": "#/$defs/DurationAsString"
        },
        "pinpoint_poll_interval": {
          "$ref": "#/$defs/DurationAsString"
        }
      },
      "additionalProperties": false,
      "type": "object"
    },
    "TriggerCondition": {
      "properties": {
        "param": {
          "type": "string"
        },
        "values": {
          "items": {
            "type": "string"
          },
          "type": "array"
        }
      },
      "additionalProperties": false,
      "type": "object",
      "required": [
        "param",
        "values"
      ]
    },
    "VisibilityConfig": {
      "properties": {
        "provider_name": {
          "type": "string"
        },
        "sources": {
          "patternProperties": {
            ".*": {
              "$ref": "#/$defs/VisibilitySourceConfig"
            }
          },
          "type": "object"
        },
        "show_only_public_traces": {
          "type": "boolean"
        },
        "override_gcs": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "type": "object",
      "required": [
        "provider_name",
        "sources"
      ]
    },
    "VisibilitySourceConfig": {
      "properties": {
        "git_repo": {
          "type": "string"
        },
        "path": {
          "type": "string"
        },
        "rule_prefix": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "type": "object",
      "required": [
        "git_repo",
        "path",
        "rule_prefix"
      ]
    }
  }
}

=== google/skia-buildbot/perf/configs/spanner/crystalball.json
{
    "URL": "https://cb-perf.corp.goog",
    "contact": "android-crystalball-eng@google.com",
    "feedback_url": "https://issuetracker.google.com/issues/new?component=1547614&template=1970127",
    "trace_sample_proportion": 0.2,
    "notify_config": {
      "notifications": "none"
    },
    "auth_config": {
      "header_name": "X-WEBAUTH-USER"
    },
    "data_store_config": {
      "datastore_type": "spanner",
      "connection_string": "postgresql://root@localhost:5432/crystalball?sslmode=disable",
      "tile_size": 8192,
      "min_db_connections": 5
    },
    "ingestion_config": {
      "source_config": {
        "source_type": "gcs",
        "project": "skia-public",
        "topic": "perf-ingestion-crystalball",
        "subscription": "perf-ingestion-crystalball-prod",
        "sources": [
          "gs://crystalball-perf/ingest"
        ]
      },
      "branches": [],
      "file_ingestion_pubsub_topic_name": ""
    },
    "git_repo_config": {
      "provider": "gitiles",
      "url": "https://android.googlesource.com/platform/superproject",
      "dir": "/tmp/crystalball",
      "debounce_commit_url": false,
      "branch": "androidx-main",
      "start_commit": "1f0b8f89aa85265e67f4c8c9a64f404e5f964391"
    },
    "query_config": {
      "default_url_values": {
        "plotSummary": "true",
        "useTestPicker": "true",
        "showZero": "true",
        "enable_chart_tooltip": "true",
        "show_google_plot": "true",
        "use_titles": "true"
      }
    },
    "data_point_config": {
      "enable_point_links": true,
      "show_json_file_display": true,
      "always_show_commit_info": true
    },
    "optimize_sqltracestore": true,
    "show_triage_link": true
}

=== google/skia-buildbot/perf/configs/fuchsia-public.json
{
    "URL": "https://fuchsia-perf.luci.app",
    "allowed_hosts": [],
    "contact": "browser-perf-engprod@google.com",
    "feedback_url": "https://issuetracker.google.com/issues/new?component=1547614&template=1970127",
    "trace_sample_proportion": 0.01,
    "notify_config": {
      "notifications": "html_email"
    },
    "auth_config": {
      "header_name": "X-WEBAUTH-USER"
    },
    "data_store_config": {
      "datastore_type": "cockroachdb",
      "connection_string": "postgresql://root@perf-cockroachdb-public:26257/fuchsia_pub?sslmode=disable",
      "tile_size": 256
    },
    "ingestion_config": {
      "source_config": {
        "source_type": "gcs",
        "project": "skia-public",
        "topic": "perf-ingestion-fuchsia-public",
        "subscription": "perf-ingestion-fuchsia-public-prod",
        "sources": [
          "gs://fuchsia-perf-public/ingest"
        ]
      },
      "branches": [],
      "file_ingestion_pubsub_topic_name": ""
    },
    "git_repo_config": {
      "provider": "gitiles",
      "url": "https://fuchsia.googlesource.com/integration",
      "dir": "/tmp/checkout",
      "debounce_commit_url": false,
      "file_change_marker": "",
      "start_commit": "a3b0fd61c1926bef019904ab5680aa2a78263711"
    },
    "query_config": {
      "default_url_values": {
        "plotSummary": "true",
        "showZero": "false"
      }
    }
  }

=== google/skia-buildbot/perf/configs/emscripten-perf-public.json
{
  "URL": "https://emscripten-perf.luci.app",
  "contact": "https://github.com/emscripten-core/emscripten/issues",
  "trace_sample_proportion": 0.01,
  "bug_host_url": "",
  "filter_parent_traces": true,
  "notify_config": {
    "notifications": "none"
  },
  "auth_config": {
    "header_name": "X-WEBAUTH-USER"
  },
  "data_store_config": {
    "datastore_type": "cockroachdb",
    "connection_string": "postgresql://root@perf-cockroachdb-public:26257/emscripten_int?sslmode=disable",
    "tile_size": 256
  },
  "ingestion_config": {
    "source_config": {
      "source_type": "gcs",
      "project": "skia-public",
      "topic": "perf-ingestion-emscripten-public-perf",
      "subscription": "perf-ingestion-emscripten-public-perf-prod",
      "sources": [
        "gs://emscripten-perf-public/ingest"
      ]
    },
    "branches": [],
    "file_ingestion_pubsub_topic_name": ""
  },
  "git_repo_config": {
    "provider": "gitiles",
    "url": "https://chromium.googlesource.com/emscripten-releases",
    "dir": "/tmp/emscripten",
    "debounce_commit_url": false
  }
}

=== google/skia-buildbot/perf/configs/devtools-frontend.json
{
    "URL": "https://devtools-frontend-perf.corp.goog",
    "allowed_hosts": [],
    "trace_sample_proportion": 1.0,
    "contact": "browser-perf-engprod@google.com",
    "invalid_param_char_regex": "([^a-zA-Z0-9!~@#$%^&*()+ :\\._\\-])",
    "fetch_chrome_perf_anomalies": true,
    "filter_parent_traces": true,
    "feedback_url": "http://go/berf-skia-feedback",
    "chat_url": "http://go/berf-skia-chat",
    "notify_config": {
        "notifications": "none"
    },
    "auth_config": {
        "header_name": "X-WEBAUTH-USER"
    },
    "data_store_config": {
        "datastore_type": "cockroachdb",
        "connection_string": "postgresql://root@perf-cockroachdb-public:26257/devtools_frontend?sslmode=disable",
        "tile_size": 8192,
        "enable_follower_reads": true
    },
    "ingestion_config": {
        "source_config": {
            "source_type": "gcs",
            "project": "skia-public",
            "topic": "perf-ingestion-devtools-frontend-perf",
            "subscription": "perf-ingestion-devtools-frontend-perf-prod",
            "dl_topic": "perf-ingestion-devtools-frontend-perf-dl",
            "dl_subscription": "perf-ingestion-devtools-frontend-perf-dl-prod",
            "sources": [
                "gs://devtools-frontend-perf/ingest"
            ]
        },
        "branches": [],
        "file_ingestion_pubsub_topic_name": ""
    },
    "git_repo_config": {
        "provider": "gitiles",
        "url": "https://chromium.googlesource.com/devtools/devtools-frontend/",
        "dir": "/tmp/checkout",
        "debounce_commit_url": false,
        "start_commit": "2ade89ddd0362e74d52f9928f448e448c625937e"
    }
}
