=== google/skia-buildbot/perf/go/config/validate/instanceConfigSchema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://go.skia.org/infra/perf/go/config/instance-config",
  "$ref": "#/$defs/InstanceConfig",
  "$defs": {
    "AnomalyConfig": {
      "properties": {
        "settling_time": {
          "$ref": "#/$defs/DurationAsString"
        },
        "default_refiner": {
          "type": "string"
        },
        "stepfit_unaligned": {
          "type": "boolean"
        },
        "process_alert_configs_worker_count": {
          "type": "integer"
        },
        "backfill_topic_name": {
          "type": "string"
        },
        "backfill_concurrency": {
          "type": "integer"
        }
      },
      "additionalProperties": false,
      "type": "object"
    },
    "ApplyDefault": {
      "properties": {
        "param": {
          "type": "string"
        },
        "values": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "select_only_first": {
          "type": "boolean"
        }
      },
      "additionalProperties": false,
      "type": "object",
      "required": [
        "param",
        "values",
        "select_only_first"
      ]
    },
    "AuthConfig": {
      "properties": {
        "header_name": {
          "type": "string"
        },
        "email_regex": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "type": "object",
      "required": [
        "header_name"
      ]
    },
    "CacheConfig": {
      "properties": {
        "memcached_servers": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "namespace": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "type": "object",
      "required": [
        "memcached_servers",
        "namespace"
      ]
    },
    "ConditionalDefaultRule": {
      "properties": {
        "trigger": {
          "$ref": "#/$defs/TriggerCondition"
        },
        "apply": {
          "items": {
            "$ref": "#/$defs/ApplyDefault"
          },
          "type": "array"
        }
      },
      "additionalProperties": false,
      "type": "object",
      "required": [
        "trigger",
        "apply"
      ]
    },
    "DataPointConfig": {
      "properties": {
        "keys_for_commit_range": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "keys_for_useful_links": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "skip_commit_detail_display": {
          "type": "boolean"
        },
        "enable_point_links": {
          "type": "boolean"
        },
        "show_json_file_display": {
          "type": "boolean"
        },
        "always_show_commit_info": {
          "type": "boolean"
        }
      },
      "additionalProperties": false,
      "type": "object"
    },
    "DataStoreConfig": {
      "properties": {
        "datastore_type": {
          "type": "string"
        },
        "connection_string": {
          "type": "string"
        },
        "tile_size": {
          "type": "integer"
        },
        "cache": {
          "$ref": "#/$defs/CacheConfig"
        },
        "enable_follower_reads": {
          "type": "boolean"
        },
        "min_db_connections": {
          "type": "integer"
        },
        "query_traces_pool_size": {
          "type": "integer"
        },
        "query_traces_chunk_size": {
          "type": "integer"
        },
        "traceparams_param_indexes": {
          "items": {
            "type": "string"
          },
          "type": "array"
        }
      },
      "additionalProperties": false,
      "type": "object",
      "required": [
        "datastore_type",
        "connection_string",
        "tile_size"
      ]
    },
    "DurationAsString": {
      "type": "string",
      "title": "Duration",
      "description": "A golang time.Duration serialized as a string."
    },
    "Experiments": {
      "properties": {
        "override_bug_component": {
          "type": "boolean"
        },
        "remove_default_stat_value": {
          "type": "boolean"
        },
        "enable_skia_bridge_aggregation": {
          "type": "boolean"
        },
        "preflight_subqueries_for_existing_keys": {
          "type": "boolean"
        },
        "progress_use_redis_cache": {
          "type": "boolean"
        },
        "regressions_trace_id_field": {
          "type": "boolean"
        },
        "df_iter_trace_slicer": {
          "type": "boolean"
        },
        "trace_transform": {
          "type": "boolean"
        }
      },
      "additionalProperties": false,
      "type": "object"
    },
    "ExtraLinks": {
      "properties": {
        "name": {
          "type": "string"
        },
        "title": {
          "type": "string"
        },
        "links": {
          "items": {
            "$ref": "#/$defs/FavoritesSectionLinkConfig"
          },
          "type": "array"
        }
      },
      "additionalProperties": false,
      "type": "object",
      "required": [
        "name",
        "title",
        "links"
      ]
    },
    "Favorites": {
      "properties": {
        "sections": {
          "items": {
            "$ref": "#/$defs/FavoritesSectionConfig"
          },
          "type": "array"
        }
      },
      "additionalProperties": false,
      "type": "object",
      "required": [
        "sections"
      ]
    },
    "FavoritesSectionConfig": {
      "properties": {
        "name": {
          "type": "string"
        },
        "links": {
          "items": {
            "$ref": "#/$defs/FavoritesSectionLinkConfig"
          },
          "type": "array"
        }
      },
      "additionalProperties": false,
      "type": "object",
      "required": [
        "name",
        "links"
      ]
    },
    "FavoritesSectionLinkConfig": {
      "properties": {
        "id": {
          "type": "string"
        },
        "text": {
          "type": "string"
        },
        "href": {
          "type": "string"
        },
        "description": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "type": "object",
      "required": [
        "text",
        "href",
        "description"
      ]
    },
    "GitRepoConfig": {
      "properties": {
        "git_auth_type": {
          "type": "string"
        },
        "provider": {
          "type": "string"
        },
        "start_commit": {
          "type": "string"
        },
        "url": {
          "type": "string"
        },
        "dir": {
          "type": "string"
        },
        "file_change_marker": {
          "type": "string"
        },
        "debounce_commit_url": {
          "type": "boolean"
        },
        "commit_url": {
          "type": "string"
        },
        "commit_number_regex": {
          "type": "string"
        },
        "branch": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "type": "object",
      "required": [
        "provider",
        "url",
        "dir"
      ]
    },
    "IngestionConfig": {
      "properties": {
        "source_config": {
          "$ref": "#/$defs/SourceConfig"
        },
        "branches": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "file_ingestion_pubsub_topic_name": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "type": "object",
      "required": [
        "source_config",
        "branches",
        "file_ingestion_pubsub_topic_name"
      ]
    },
    "InstanceConfig": {
      "properties": {
        "URL": {
          "type": "string"
        },
        "instance_name": {
          "type": "string"
        },
        "header_image_url": {
          "type": "string"
        },
        "landing_page_rel_path": {
          "type": "string"
        },
        "backend_host_url": {
          "type": "string"
        },
        "allowed_hosts": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "contact": {
          "type": "string"
        },
        "invalid_param_char_regex": {
          "type": "string"
        },
        "fetch_chrome_perf_anomalies": {
          "type": "boolean"
        },
        "fetch_anomalies_from_sql": {
          "type": "boolean"
        },
        "switch_between_anomaly_sources": {
          "type": "boolean"
        },
        "feedback_url": {
          "type": "string"
        },
        "chat_url": {
          "type": "string"
        },
        "help_url_override": {
          "type": "string"
        },
        "bug_host_url": {
          "type": "string"
        },
        "favorites": {
          "$ref": "#/$defs/Favorites"
        },
        "extra_links": {
          "$ref": "#/$defs/ExtraLinks"
        },
        "filter_parent_traces": {
          "type": "boolean"
        },
        "trace_sample_proportion": {
          "type": "number"
        },
        "trace_format": {
          "type": "string"
        },
        "need_alert_action": {
          "type": "boolean"
        },
        "use_regression2_schema": {
          "type": "boolean"
        },
        "auth_config": {
          "$ref": "#/$defs/AuthConfig"
        },
        "data_store_config": {
          "$ref": "#/$defs/DataStoreConfig"
        },
        "ingestion_config": {
          "$ref": "#/$defs/IngestionConfig"
        },
        "git_repo_config": {
          "$ref": "#/$defs/GitRepoConfig"
        },
        "notify_config": {
          "$ref": "#/$defs/NotifyConfig"
        },
        "issue_tracker_config": {
          "$ref": "#/$defs/IssueTrackerConfig"
        },
        "anomaly_config": {
          "$ref": "#/$defs/AnomalyConfig"
        },
        "query_config": {
          "$ref": "#/$defs/QueryConfig"
        },
        "temporal_config": {
          "$ref": "#/$defs/TemporalConfig"
        },
        "data_point_config": {
          "$ref": "#/$defs/DataPointConfig"
        },
        "visibility_config": {
          "$ref": "#/$defs/VisibilityConfig"
        },
        "enable_sheriff_config": {
          "type": "boolean"
        },
        "sheriff_configs_to_notify": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "maintenance_config": {
          "$ref": "#/$defs/MaintenanceConfig"
        },
        "ga_measurement_id": {
          "type": "string"
        },
        "new_alerts_page": {
          "type": "boolean"
        },
        "optimize_sqltracestore": {
          "type": "boolean"
        },
        "experiments": {
          "$ref": "#/$defs/Experiments"
        },
        "show_triage_link": {
          "type": "boolean"
        },
        "show_bisect_btn": {
          "type": "boolean"
        },
        "show_hash_ranges_in_tooltip": {
          "type": "boolean"
        },
        "allow_multiple_regressions_per_alert_id": {
          "type": "boolean"
        },
        "enable_v2_ui": {
          "type": "boolean"
        },
        "default_to_explore_v2": {
          "type": "boolean"
        },
        "default_to_manual_plot_mode": {
          "type": "boolean"
        },
        "demo": {
          "type": "boolean"
        }
      },
      "additionalProperties": false,
      "type": "object",
      "required": [
        "URL",
        "contact",
        "data_store_config",
        "ingestion_config",
        "git_repo_config",
        "notify_config"
      ]
    },
    "IssueTrackerConfig": {
      "properties": {
        "notification_type": {
          "type": "string"
        },
        "issue_tracker_api_key_secret_project": {
          "type": "string"
        },
        "issue_tracker_api_key_secret_name": {
          "type": "string"
        },
        "culprit_subject": {
          "type": "string"
        },
        "culprit_body": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "anomaly_report_subject": {
          "type": "string"
        },
        "anomaly_report_body": {
          "items": {
            "type": "string"
          },
          "type": "array"
        }
      },
      "additionalProperties": false,
      "type": "object",
      "required": [
        "notification_type"
      ]
    },
    "MaintenanceConfig": {
      "properties": {
        "gitiles_repo_url": {
          "type": "string"
        },
        "sheriff_config_path": {
          "type": "string"
        },
        "fallback_to_lucicfg": {
          "type": "boolean"
        }
      },
      "additionalProperties": false,
      "type": "object",
      "required": [
        "fallback_to_lucicfg"
      ]
    },
    "NotifyConfig": {
      "properties": {
        "notifications": {
          "type": "string"
        },
        "subject": {
          "type": "string"
        },
        "body": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "missing_subject": {
          "type": "string"
        },
        "missing_body": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "data_provider": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "type": "object",
      "required": [
        "notifications"
      ]
    },
    "QueryCacheConfig": {
      "properties": {
        "type": {
          "type": "string"
        },
        "level1_cache_key": {
          "type": "string"
        },
        "level1_cache_values": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "level2_cache_key": {
          "type": "string"
        },
        "level2_cache_values": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "enabled": {
          "type": "boolean"
        }
      },
      "additionalProperties": false,
      "type": "object",
      "required": [
        "type"
      ]
    },
    "QueryConfig": {
      "properties": {
        "include_params": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "default_param_selections": {
          "patternProperties": {
            ".*": {
              "items": {
                "type": "string"
              },
              "type": "array"
            }
          },
          "type": "object"
        },
        "default_url_values": {
          "patternProperties": {
            ".*": {
              "type": "string"
            }
          },
          "type": "object"
        },
        "cache_config": {
          "$ref": "#/$defs/QueryCacheConfig"
        },
        "redis_config": {
          "$ref": "#/$defs/RedisConfig"
        },
        "query_commit_chunk_size": {
          "type": "integer"
        },
        "max_empty_tiles": {
          "type": "integer"
        },
        "default_range": {
          "type": "integer"
        },
        "default_xaxis_domain": {
          "type": "string"
        },
        "conditional_defaults": {
          "items": {
            "$ref": "#/$defs/ConditionalDefaultRule"
          },
          "type": "array"
        },
        "default_trigger_priority": {
          "patternProperties": {
            ".*": {
              "items": {
                "type": "string"
              },
              "type": "array"
            }
          },
          "type": "object"
        }
      },
      "additionalProperties": false,
      "type": "object"
    },
    "RedisConfig": {
      "properties": {
        "project": {
          "type": "string"
        },
        "zone": {
          "type": "string"
        },
        "instance": {
          "type": "string"
        },
        "cache_expiration_minutes": {
          "type": "integer"
        }
      },
      "additionalProperties": false,
      "type": "object"
    },
    "SourceConfig": {
      "properties": {
        "source_type": {
          "type": "string"
        },
        "project": {
          "type": "string"
        },
        "topic": {
          "type": "string"
        },
        "subscription": {
          "type": "string"
        },
        "dl_topic": {
          "type": "string"
        },
        "dl_subscription": {
          "type": "string"
        },
        "sources": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "reject_if_name_matches": {
          "type": "string"
        },
        "accept_if_name_matches": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "type": "object",
      "required": [
        "source_type",
        "project",
        "topic",
        "subscription",
        "sources"
      ]
    },
    "TemporalConfig": {
      "properties": {
        "host_port": {
          "type": "string"
        },
        "namespace": {
          "type": "string"
        },
        "grouping_task_queue": {
          "type": "string"
        },
        "pinpoint_task_queue": {
          "type": "string"
        },
        "wait_time_for_anomaly_clustering_window": {
          "$ref": "#/$defs/DurationAsString"
        },
        "pinpoint_poll_interval": {
          "$ref": "#/$defs/DurationAsString"
        }
      },
      "additionalProperties": false,
      "type": "object"
    },
    "TriggerCondition": {
      "properties": {
        "param": {
          "type": "string"
        },
        "values": {
          "items": {
            "type": "string"
          },
          "type": "array"
        }
      },
      "additionalProperties": false,
      "type": "object",
      "required": [
        "param",
        "values"
      ]
    },
    "VisibilityConfig": {
      "properties": {
        "provider_name": {
          "type": "string"
        },
        "sources": {
          "patternProperties": {
            ".*": {
              "$ref": "#/$defs/VisibilitySourceConfig"
            }
          },
          "type": "object"
        },
        "show_only_public_traces": {
          "type": "boolean"
        },
        "override_gcs": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "type": "object",
      "required": [
        "provider_name",
        "sources"
      ]
    },
    "VisibilitySourceConfig": {
      "properties": {
        "git_repo": {
          "type": "string"
        },
        "path": {
          "type": "string"
        },
        "rule_prefix": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "type": "object",
      "required": [
        "git_repo",
        "path",
        "rule_prefix"
      ]
    }
  }
}

=== google/skia-buildbot/perf/configs/v8.json
{
  "URL": "https://v8-perf.skia.org",
  "contact": "https://bugs.chromium.org/p/v8/issues/list?q=component%3ATools&can=2",
  "trace_sample_proportion": 0.01,
  "notify_config": {
    "notifications": "html_email"
  },
  "auth_config": {
    "header_name": "X-WEBAUTH-USER"
  },
  "data_store_config": {
    "datastore_type": "cockroachdb",
    "connection_string": "postgresql://root@perf-cockroachdb3-public:26277/v8?sslmode=disable",
    "tile_size": 256
  },
  "ingestion_config": {
    "source_config": {
      "source_type": "gcs",
      "project": "skia-public",
      "topic": "perf-ingestion-v8-production-restore",
      "subscription": "perf-ingestion-v8-production-restore-prod",
      "sources": [
        "gs://v8_perf_skia_prod/v8/cq/",
        "gs://v8_perf_skia_prod/v8/chromeperf/"
      ]
    },
    "branches": [],
    "file_ingestion_pubsub_topic_name": ""
  },
  "git_repo_config": {
    "provider": "gitiles",
    "url": "https://chromium.googlesource.com/v8/v8.git",
    "dir": "/tmp/v8",
    "debounce_commit_url": false
  },
  "query_config": {
    "default_url_values": {
      "plotSummary": "true",
      "showZero": "false"
    }
  }
}

=== google/skia-buildbot/perf/configs/spanner/eskia-internal.json
{
    "URL": "https://eskia-perf.corp.goog",
    "landing_page_rel_path": "/m/",
    "allowed_hosts": [],
    "trace_sample_proportion": 1.0,
    "contact": "eskia-team@google.com",
    "invalid_param_char_regex": "([^a-zA-Z0-9!~@#$%^&*()+ :\\._\\-])",
    "feedback_url": "http://go/berf-skia-feedback",
    "chat_url": "http://go/berf-skia-chat",
    "notify_config": {
        "notifications": "none"
    },
    "auth_config": {
        "header_name": "X-WEBAUTH-USER"
    },
    "data_store_config": {
        "datastore_type": "spanner",
        "connection_string": "postgresql://root@localhost:5432/eskia?sslmode=disable",
        "tile_size": 256,
        "enable_follower_reads": true
    },
    "ingestion_config": {
        "source_config": {
            "source_type": "gcs",
            "project": "skia-public",
            "topic": "perf-ingestion-eskia",
            "subscription": "perf-ingestion-eskia-prod",
            "sources": [
                "gs://eskia-perf/ingest"
            ]
        },
        "branches": [],
        "file_ingestion_pubsub_topic_name": ""
    },
    "git_repo_config": {
        "provider": "gitiles",
        "url": "https://skia.googlesource.com/eskia",
        "dir": "/tmp/checkout",
        "debounce_commit_url": false,
        "start_commit": "1a753890e24ae62fc93fb1f97c16cab2c2c711d0"
    },
    "issue_tracker_config": {
        "notification_type": "issuetracker",
        "issue_tracker_api_key_secret_project": "skia-infra-public",
        "issue_tracker_api_key_secret_name": "perf-issue-tracker-apikey"
    },
    "optimize_sqltracestore": true
}

=== google/skia-buildbot/perf/configs/spanner/android2-autopush.json
{
    "URL": "https://androidx2-perf-autopush.luci.app",
    "instance_name": "AndroidX (Autopush)",
    "landing_page_rel_path": "/e2",
    "header_image_url": "/dist/images/androidx.svg",
    "contact": "http://go/androidx-discuss",
    "ga_measurement_id": "G-YDQJ6YQGFM",
    "feedback_url": "https://issuetracker.google.com/issues/new?component=1547614&template=1970127",
    "trace_sample_proportion": 0.2,
    "notify_config": {
      "notifications": "markdown_issuetracker",
      "data_provider": "android",
      "subject": "{{ .Alert.DisplayName }} - Regression between {{ .PreviousCommit.Subject }} and {{ .RegressionCommit.Subject }}",
      "body": [
            "Perf Regression ({{ .Cluster.StepFit.Status }}) found, matching {{ .Cluster.Num }} tracked metrics from benchmarks.",
            "",
            "To triage this regression, see the guide at [go/androidx-bench-triage](http://go/androidx-bench-triage).",
            "",
            "* [Graph on dashboard]({{ .DashboardUrl }})",
            "* [Alert details]({{ .URL }}/g/t/{{ .RegressionCommit.GitHash }})",
            "* [CLs in range]({{ .GetBuildIdUrlDiff }})",
            "* [{{ .Alert.DisplayName }} alert config]({{ .URL }}/a/?{{ .Alert.IDAsString }})",
            "",
            "Tests affected:",
            "```",
            "{{ range index .Tests }} {{ . }}",
            "{{end}}```",
            ""
        ]
    },
    "issue_tracker_config": {
      "notification_type": "issuetracker",
      "issue_tracker_api_key_secret_project": "skia-infra-public",
      "issue_tracker_api_key_secret_name": "perf-issue-tracker-apikey"
    },
    "auth_config": {
      "header_name": "X-WEBAUTH-USER"
    },
    "data_store_config": {
      "datastore_type": "spanner",
      "connection_string": "postgresql://root@127.0.0.1:5432/androidx_autopush?sslmode=disable",
      "tile_size": 512,
      "min_db_connections": 5
    },
    "experiments": {
        "trace_transform": true
    },
    "ingestion_config": {
      "source_config": {
        "source_type": "gcs",
        "project": "skia-public",
        "topic": "perf-ingestion-android2-autopush",
        "subscription": "perf-ingestion-android2-autopush-prod",
        "sources": [
          "gs://android-perf-2/android2"
        ]
      },
      "branches": [],
      "file_ingestion_pubsub_topic_name": ""
    },
    "git_repo_config": {
      "provider": "gitiles",
      "url": "https://android.googlesource.com/platform/superproject",
      "dir": "/tmp/androidx",
      "debounce_commit_url": false,
      "branch": "androidx-main",
      "start_commit": "5f8b9aa0feafff7548336998a17723cb792cdb53"
    },
    "anomaly_config": {
      "settling_time": "5h"
    },
    "query_config": {
      "include_params": [
        "test_class",
        "test_method",
        "metric",
        "stat",
        "device_name",
        "os_version"
      ],

      "default_url_values": {
        "evenXAxisSpacing": "true",
        "plotSummary": "true",
        "useTestPicker": "true",
        "showZero": "true",
        "enable_chart_tooltip": "true",
        "show_google_plot": "true",
        "use_titles": "true"
      },
      "query_commit_chunk_size": 7000,
      "default_xaxis_domain": "date",
      "default_trigger_priority": {
        "metric": ["timeNs", "timeToInitialDisplayMs", "frameDurationCpuMs"]
      },
      "conditional_defaults": [
        {
          "trigger": {
            "param": "metric",
            "values": ["timeNs"]
          },
          "apply": [
            { "param": "stat", "values": ["min"], "select_only_first": true },
            { "param": "device_name", "values": ["sargo", "mokey"], "select_only_first": true },
            { "param": "os_version", "values": ["API_31_S", "API_34_U"], "select_only_first": true }
          ]
        },
        {
          "trigger": {
            "param": "metric",
            "values": ["timeToInitialDisplayMs"]
          },
          "apply": [
            { "param": "stat", "values": ["median"], "select_only_first": true },
            { "param": "device_name", "values": ["sargo", "mokey"], "select_only_first": true },
            { "param": "os_version", "values": ["API_31_S", "API_34_U"], "select_only_first": true }
          ]
        },
        {
          "trigger": {
            "param": "metric",
            "values": ["frameDurationCpuMs"]
          },
          "apply": [
            { "param": "stat", "values": ["P50", "P90", "P95", "P99"], "select_only_first": false },
            { "param": "device_name", "values": ["sargo", "mokey"], "select_only_first": true },
            { "param": "os_version", "values": ["API_31_S", "API_34_U"], "select_only_first": true }
          ]
        }
      ]
    },
    "data_point_config": {
      "keys_for_useful_links": [
        "ART mainline version",
        "ATI Page",
        "Build ID",
        "Device fingerprint",
        "Profiling Traces and Test Artifacts",
        "Trace",
        "Trace Iteration 0",
        "Trace Iteration 1",
        "Trace Iteration 2",
        "Trace Iteration 3",
        "Trace Iteration 4",
        "Trace Iteration 5",
        "Trace Iteration 6",
        "Trace Iteration 7",
        "Trace Iteration 8",
        "Trace Iteration 9",
        "appApkSha256",
        "testApkSha256"
      ],
      "enable_point_links": true,
      "show_json_file_display": true,
      "always_show_commit_info": true
    },
    "optimize_sqltracestore": true,
    "show_triage_link": true,
    "show_bisect_btn": false,
    "enable_v2_ui": true,
    "default_to_explore_v2": true
}

=== google/skia-buildbot/perf/configs/flutter-engine2.json
{
    "URL": "https://flutter-engine-perf.skia.org",
    "contact": "https://mail.google.com/chat/u/0/?zx=s88snihcl7ie#chat/space/AAAAm69vf-M",
    "feedback_url": "https://issuetracker.google.com/issues/new?component=1547614&template=1970127",
    "trace_sample_proportion": 0.01,
    "notify_config": {
        "notifications": "html_email"
    },
    "auth_config": {
        "header_name": "X-WEBAUTH-USER"
    },
    "data_store_config": {
        "datastore_type": "cockroachdb",
        "connection_string": "postgresql://root@perf-cockroachdb3-public:26277/flutter_engine2?sslmode=disable",
        "tile_size": 4096
    },
    "ingestion_config": {
        "source_config": {
            "source_type": "gcs",
            "project": "skia-public",
            "topic": "perf-ingestion-flutter-engine2",
            "subscription": "perf-ingestion-flutter-engine2-cdb-prod",
            "sources": [
                "gs://flutter-skia-perf-prod/flutter-engine"
            ],
            "reject_if_name_matches": ".lock$"
        },
        "branches": [],
        "file_ingestion_pubsub_topic_name": ""
    },
    "git_repo_config": {
        "provider": "git",
        "url": "https://github.com/flutter/engine",
        "dir": "/tmp/flutter-engine",
        "debounce_commit_url": false,
        "commit_url": "%s/commit/%s"
    }
}
